# -*- coding: utf-8 -*-
"""assignment-4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Y13vlKn8L9pygJDVNRPOCnGmy0rHBv_l
"""

# Commented out IPython magic to ensure Python compatibility.
import sqlalchemy
user = 'peter'
password = 'PeterWoW1!'
sql_conn_str = 'postgresql://{user}:{password}@grepp-data.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev'.format(
    user=user,
    password=password
)
engine = sqlalchemy.create_engine(sql_conn_str)
# %load_ext sql
# %sql postgresql://peter:PeterWoW1!@grepp-data.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
echo=True

query = '''
SELECT cohort_month, 
  DATEDIFF(MONTH, cohort_month, visited_month) + 1 AS month_N, 
  COUNT(DISTINCT cohort.userid) AS users_count
FROM (
    SELECT usc.userid, MIN(DATE_TRUNC('month', st.ts)) cohort_month
    FROM raw_data.user_session_channel usc
    JOIN raw_data.session_timestamp st
    ON st.sessionid = usc.sessionid
    GROUP BY 1
) cohort
JOIN (
    SELECT DISTINCT usc.userid, DATE_TRUNC('month', st.ts) visited_month
    FROM raw_data.user_session_channel usc
    JOIN raw_data.session_timestamp st
    ON st.sessionid = usc.sessionid
) visit
ON cohort.cohort_month <= visit.visited_month AND cohort.userid = visit.userid
GROUP BY 1, 2
ORDER BY 1, 2;
'''

import pandas as pd

df = pd.read_sql_query(query, engine)

print(df)

pd.pivot_table(df, index = 'cohort_month', columns='month_n', values='users_count')

